// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Delivery is the predicate function for delivery builders.
type Delivery func(*sql.Selector)

// DeliveryItem is the predicate function for deliveryitem builders.
type DeliveryItem func(*sql.Selector)
