// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"delivery/pkg/ent/delivery"
	"delivery/pkg/ent/deliveryitem"
	"delivery/pkg/ent/predicate"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeliveryItemQuery is the builder for querying DeliveryItem entities.
type DeliveryItemQuery struct {
	config
	ctx          *QueryContext
	order        []deliveryitem.OrderOption
	inters       []Interceptor
	predicates   []predicate.DeliveryItem
	withDelivery *DeliveryQuery
	withFKs      bool
	modifiers    []func(*sql.Selector)
	loadTotal    []func(context.Context, []*DeliveryItem) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeliveryItemQuery builder.
func (diq *DeliveryItemQuery) Where(ps ...predicate.DeliveryItem) *DeliveryItemQuery {
	diq.predicates = append(diq.predicates, ps...)
	return diq
}

// Limit the number of records to be returned by this query.
func (diq *DeliveryItemQuery) Limit(limit int) *DeliveryItemQuery {
	diq.ctx.Limit = &limit
	return diq
}

// Offset to start from.
func (diq *DeliveryItemQuery) Offset(offset int) *DeliveryItemQuery {
	diq.ctx.Offset = &offset
	return diq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (diq *DeliveryItemQuery) Unique(unique bool) *DeliveryItemQuery {
	diq.ctx.Unique = &unique
	return diq
}

// Order specifies how the records should be ordered.
func (diq *DeliveryItemQuery) Order(o ...deliveryitem.OrderOption) *DeliveryItemQuery {
	diq.order = append(diq.order, o...)
	return diq
}

// QueryDelivery chains the current query on the "delivery" edge.
func (diq *DeliveryItemQuery) QueryDelivery() *DeliveryQuery {
	query := (&DeliveryClient{config: diq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := diq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := diq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deliveryitem.Table, deliveryitem.FieldID, selector),
			sqlgraph.To(delivery.Table, delivery.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deliveryitem.DeliveryTable, deliveryitem.DeliveryColumn),
		)
		fromU = sqlgraph.SetNeighbors(diq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeliveryItem entity from the query.
// Returns a *NotFoundError when no DeliveryItem was found.
func (diq *DeliveryItemQuery) First(ctx context.Context) (*DeliveryItem, error) {
	nodes, err := diq.Limit(1).All(setContextOp(ctx, diq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deliveryitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (diq *DeliveryItemQuery) FirstX(ctx context.Context) *DeliveryItem {
	node, err := diq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeliveryItem ID from the query.
// Returns a *NotFoundError when no DeliveryItem ID was found.
func (diq *DeliveryItemQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = diq.Limit(1).IDs(setContextOp(ctx, diq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deliveryitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (diq *DeliveryItemQuery) FirstIDX(ctx context.Context) int {
	id, err := diq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeliveryItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeliveryItem entity is found.
// Returns a *NotFoundError when no DeliveryItem entities are found.
func (diq *DeliveryItemQuery) Only(ctx context.Context) (*DeliveryItem, error) {
	nodes, err := diq.Limit(2).All(setContextOp(ctx, diq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deliveryitem.Label}
	default:
		return nil, &NotSingularError{deliveryitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (diq *DeliveryItemQuery) OnlyX(ctx context.Context) *DeliveryItem {
	node, err := diq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeliveryItem ID in the query.
// Returns a *NotSingularError when more than one DeliveryItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (diq *DeliveryItemQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = diq.Limit(2).IDs(setContextOp(ctx, diq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deliveryitem.Label}
	default:
		err = &NotSingularError{deliveryitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (diq *DeliveryItemQuery) OnlyIDX(ctx context.Context) int {
	id, err := diq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeliveryItems.
func (diq *DeliveryItemQuery) All(ctx context.Context) ([]*DeliveryItem, error) {
	ctx = setContextOp(ctx, diq.ctx, ent.OpQueryAll)
	if err := diq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeliveryItem, *DeliveryItemQuery]()
	return withInterceptors[[]*DeliveryItem](ctx, diq, qr, diq.inters)
}

// AllX is like All, but panics if an error occurs.
func (diq *DeliveryItemQuery) AllX(ctx context.Context) []*DeliveryItem {
	nodes, err := diq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeliveryItem IDs.
func (diq *DeliveryItemQuery) IDs(ctx context.Context) (ids []int, err error) {
	if diq.ctx.Unique == nil && diq.path != nil {
		diq.Unique(true)
	}
	ctx = setContextOp(ctx, diq.ctx, ent.OpQueryIDs)
	if err = diq.Select(deliveryitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (diq *DeliveryItemQuery) IDsX(ctx context.Context) []int {
	ids, err := diq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (diq *DeliveryItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, diq.ctx, ent.OpQueryCount)
	if err := diq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, diq, querierCount[*DeliveryItemQuery](), diq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (diq *DeliveryItemQuery) CountX(ctx context.Context) int {
	count, err := diq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (diq *DeliveryItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, diq.ctx, ent.OpQueryExist)
	switch _, err := diq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (diq *DeliveryItemQuery) ExistX(ctx context.Context) bool {
	exist, err := diq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeliveryItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (diq *DeliveryItemQuery) Clone() *DeliveryItemQuery {
	if diq == nil {
		return nil
	}
	return &DeliveryItemQuery{
		config:       diq.config,
		ctx:          diq.ctx.Clone(),
		order:        append([]deliveryitem.OrderOption{}, diq.order...),
		inters:       append([]Interceptor{}, diq.inters...),
		predicates:   append([]predicate.DeliveryItem{}, diq.predicates...),
		withDelivery: diq.withDelivery.Clone(),
		// clone intermediate query.
		sql:  diq.sql.Clone(),
		path: diq.path,
	}
}

// WithDelivery tells the query-builder to eager-load the nodes that are connected to
// the "delivery" edge. The optional arguments are used to configure the query builder of the edge.
func (diq *DeliveryItemQuery) WithDelivery(opts ...func(*DeliveryQuery)) *DeliveryItemQuery {
	query := (&DeliveryClient{config: diq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	diq.withDelivery = query
	return diq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ProductName string `json:"productName,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeliveryItem.Query().
//		GroupBy(deliveryitem.FieldProductName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (diq *DeliveryItemQuery) GroupBy(field string, fields ...string) *DeliveryItemGroupBy {
	diq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeliveryItemGroupBy{build: diq}
	grbuild.flds = &diq.ctx.Fields
	grbuild.label = deliveryitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ProductName string `json:"productName,omitempty"`
//	}
//
//	client.DeliveryItem.Query().
//		Select(deliveryitem.FieldProductName).
//		Scan(ctx, &v)
func (diq *DeliveryItemQuery) Select(fields ...string) *DeliveryItemSelect {
	diq.ctx.Fields = append(diq.ctx.Fields, fields...)
	sbuild := &DeliveryItemSelect{DeliveryItemQuery: diq}
	sbuild.label = deliveryitem.Label
	sbuild.flds, sbuild.scan = &diq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeliveryItemSelect configured with the given aggregations.
func (diq *DeliveryItemQuery) Aggregate(fns ...AggregateFunc) *DeliveryItemSelect {
	return diq.Select().Aggregate(fns...)
}

func (diq *DeliveryItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range diq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, diq); err != nil {
				return err
			}
		}
	}
	for _, f := range diq.ctx.Fields {
		if !deliveryitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if diq.path != nil {
		prev, err := diq.path(ctx)
		if err != nil {
			return err
		}
		diq.sql = prev
	}
	return nil
}

func (diq *DeliveryItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeliveryItem, error) {
	var (
		nodes       = []*DeliveryItem{}
		withFKs     = diq.withFKs
		_spec       = diq.querySpec()
		loadedTypes = [1]bool{
			diq.withDelivery != nil,
		}
	)
	if diq.withDelivery != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, deliveryitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeliveryItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeliveryItem{config: diq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(diq.modifiers) > 0 {
		_spec.Modifiers = diq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, diq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := diq.withDelivery; query != nil {
		if err := diq.loadDelivery(ctx, query, nodes, nil,
			func(n *DeliveryItem, e *Delivery) { n.Edges.Delivery = e }); err != nil {
			return nil, err
		}
	}
	for i := range diq.loadTotal {
		if err := diq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (diq *DeliveryItemQuery) loadDelivery(ctx context.Context, query *DeliveryQuery, nodes []*DeliveryItem, init func(*DeliveryItem), assign func(*DeliveryItem, *Delivery)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*DeliveryItem)
	for i := range nodes {
		if nodes[i].delivery_delivery_item == nil {
			continue
		}
		fk := *nodes[i].delivery_delivery_item
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(delivery.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "delivery_delivery_item" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (diq *DeliveryItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := diq.querySpec()
	if len(diq.modifiers) > 0 {
		_spec.Modifiers = diq.modifiers
	}
	_spec.Node.Columns = diq.ctx.Fields
	if len(diq.ctx.Fields) > 0 {
		_spec.Unique = diq.ctx.Unique != nil && *diq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, diq.driver, _spec)
}

func (diq *DeliveryItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deliveryitem.Table, deliveryitem.Columns, sqlgraph.NewFieldSpec(deliveryitem.FieldID, field.TypeInt))
	_spec.From = diq.sql
	if unique := diq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if diq.path != nil {
		_spec.Unique = true
	}
	if fields := diq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deliveryitem.FieldID)
		for i := range fields {
			if fields[i] != deliveryitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := diq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := diq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := diq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := diq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (diq *DeliveryItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(diq.driver.Dialect())
	t1 := builder.Table(deliveryitem.Table)
	columns := diq.ctx.Fields
	if len(columns) == 0 {
		columns = deliveryitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if diq.sql != nil {
		selector = diq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if diq.ctx.Unique != nil && *diq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range diq.predicates {
		p(selector)
	}
	for _, p := range diq.order {
		p(selector)
	}
	if offset := diq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := diq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeliveryItemGroupBy is the group-by builder for DeliveryItem entities.
type DeliveryItemGroupBy struct {
	selector
	build *DeliveryItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (digb *DeliveryItemGroupBy) Aggregate(fns ...AggregateFunc) *DeliveryItemGroupBy {
	digb.fns = append(digb.fns, fns...)
	return digb
}

// Scan applies the selector query and scans the result into the given value.
func (digb *DeliveryItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, digb.build.ctx, ent.OpQueryGroupBy)
	if err := digb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeliveryItemQuery, *DeliveryItemGroupBy](ctx, digb.build, digb, digb.build.inters, v)
}

func (digb *DeliveryItemGroupBy) sqlScan(ctx context.Context, root *DeliveryItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(digb.fns))
	for _, fn := range digb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*digb.flds)+len(digb.fns))
		for _, f := range *digb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*digb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := digb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeliveryItemSelect is the builder for selecting fields of DeliveryItem entities.
type DeliveryItemSelect struct {
	*DeliveryItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dis *DeliveryItemSelect) Aggregate(fns ...AggregateFunc) *DeliveryItemSelect {
	dis.fns = append(dis.fns, fns...)
	return dis
}

// Scan applies the selector query and scans the result into the given value.
func (dis *DeliveryItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dis.ctx, ent.OpQuerySelect)
	if err := dis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeliveryItemQuery, *DeliveryItemSelect](ctx, dis.DeliveryItemQuery, dis, dis.inters, v)
}

func (dis *DeliveryItemSelect) sqlScan(ctx context.Context, root *DeliveryItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dis.fns))
	for _, fn := range dis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
