// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"delivery/pkg/ent/deliveryitem"
	"delivery/pkg/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeliveryItemDelete is the builder for deleting a DeliveryItem entity.
type DeliveryItemDelete struct {
	config
	hooks    []Hook
	mutation *DeliveryItemMutation
}

// Where appends a list predicates to the DeliveryItemDelete builder.
func (did *DeliveryItemDelete) Where(ps ...predicate.DeliveryItem) *DeliveryItemDelete {
	did.mutation.Where(ps...)
	return did
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (did *DeliveryItemDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, did.sqlExec, did.mutation, did.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (did *DeliveryItemDelete) ExecX(ctx context.Context) int {
	n, err := did.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (did *DeliveryItemDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(deliveryitem.Table, sqlgraph.NewFieldSpec(deliveryitem.FieldID, field.TypeInt))
	if ps := did.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, did.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	did.mutation.done = true
	return affected, err
}

// DeliveryItemDeleteOne is the builder for deleting a single DeliveryItem entity.
type DeliveryItemDeleteOne struct {
	did *DeliveryItemDelete
}

// Where appends a list predicates to the DeliveryItemDelete builder.
func (dido *DeliveryItemDeleteOne) Where(ps ...predicate.DeliveryItem) *DeliveryItemDeleteOne {
	dido.did.mutation.Where(ps...)
	return dido
}

// Exec executes the deletion query.
func (dido *DeliveryItemDeleteOne) Exec(ctx context.Context) error {
	n, err := dido.did.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{deliveryitem.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (dido *DeliveryItemDeleteOne) ExecX(ctx context.Context) {
	if err := dido.Exec(ctx); err != nil {
		panic(err)
	}
}
