// Code generated by ent, DO NOT EDIT.

package ent

import (
	"delivery/pkg/ent/delivery"
	"delivery/pkg/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	deliveryFields := schema.Delivery{}.Fields()
	_ = deliveryFields
	// deliveryDescCreatedAt is the schema descriptor for created_at field.
	deliveryDescCreatedAt := deliveryFields[4].Descriptor()
	// delivery.DefaultCreatedAt holds the default value on creation for the created_at field.
	delivery.DefaultCreatedAt = deliveryDescCreatedAt.Default.(func() time.Time)
}
