package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"auth"
	"context"
	"errorwrapper"
	"user/pkg/ent"
	"user/pkg/graph/gen"

	"entgo.io/contrib/entgql"
)

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, after *entgql.Cursor[int], first *int, before *entgql.Cursor[int], last *int, where *ent.UserWhereInput) (*ent.UserConnection, error) {
	passport := auth.PassportFromContext(ctx)

	if passport.UserAuthority.IsAdmin() {
		return r.userService.Paginate(
			ctx,
			r.entClient,
			after,
			first,
			before,
			last,
			where,
		)
	} else {
		return nil, &errorwrapper.HTTPError{
			StatusCode: 401,
			Message:    "Users should have role admin",
		}
	}
}

// Query returns gen.QueryResolver implementation.
func (r *Resolver) Query() gen.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
